# Generated by Django 3.2 on 2021-04-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_adding_Author_and_BookAuthor_models_for_next_implementing_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
